PROGS_SLEEP_OVERFLOW_OBJS := sleep_overflow.o
PROGS_SLEEP_OVERFLOW_OBJS := $(PROGS_SLEEP_OVERFLOW_OBJS:%=$(TDIR)/sleep_overflow/%)
ALL_OBJS += $(PROGS_SLEEP_OVERFLOW_OBJS)

$(TDIR)/bin/sleep_overflow : $(TSTART) $(PROGS_SLEEP_OVERFLOW_OBJS) $(TLIBC)

