PROGS_MUTEX_TEST_SLEEP_OBJS := mutex_test_sleep.o
PROGS_MUTEX_TEST_SLEEP_OBJS := $(PROGS_MUTEX_TEST_SLEEP_OBJS:%=$(TDIR)/mutex_test_sleep/%)
ALL_OBJS += $(PROGS_MUTEX_TEST_SLEEP_OBJS)

$(TDIR)/bin/mutex_test_sleep : $(TSTART) $(PROGS_MUTEX_TEST_SLEEP_OBJS) $(TLIBC)
