MUTEX_TEST_DAGGER_OBJS := mutex_test.o
MUTEX_TEST_DAGGER_OBJS := $(MUTEX_TEST_DAGGER_OBJS:%=$(TDIR)/mutex_test/%)
ALL_OBJS += $(MUTEX_TEST_DAGGER_OBJS)

$(TDIR)/bin/mutex_test : $(TSTART) $(MUTEX_TEST_DAGGER_OBJS) $(TLIBC)

