PROGS_SLEEP_SIMPLE_OBJS := sleep_simple.o
PROGS_SLEEP_SIMPLE_OBJS := $(PROGS_SLEEP_SIMPLE_OBJS:%=$(TDIR)/sleep_simple/%)
ALL_OBJS += $(PROGS_SLEEP_SIMPLE_OBJS)

$(TDIR)/bin/sleep_simple : $(TSTART) $(PROGS_SLEEP_SIMPLE_OBJS) $(TLIBC)

