PROGS_SLEEP_COMPLEX_OBJS := sleep_complex.o
PROGS_SLEEP_COMPLEX_OBJS := $(PROGS_SLEEP_COMPLEX_OBJS:%=$(TDIR)/sleep_complex/%)
ALL_OBJS += $(PROGS_SLEEP_COMPLEX_OBJS)

$(TDIR)/bin/sleep_complex : $(TSTART) $(PROGS_SLEEP_COMPLEX_OBJS) $(TLIBC)

